#############################################################################
# Makefile for building: qtjscript1.app/Contents/MacOS/qtjscript1
# Generated by qmake (3.1) (Qt 5.11.2)
# Project:  qtjscript1.pro
# Template: app
# Command: /usr/local/qt511/bin/qmake -o Makefile qtjscript1.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.11 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/qt511/include -I/usr/local/qt511/include/QtWidgets -I/usr/local/qt511/include/QtGui -I/usr/local/qt511/include/QtQml -I/usr/local/qt511/include/QtNetwork -I/usr/local/qt511/include/QtCore -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/usr/local/qt511/mkspecs/macx-clang
QMAKE         = /usr/local/qt511/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/qt511/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/local/qt511/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = qtjscript11.0.0
DISTDIR = /Users/jjosburn/Documents/programming/qtjscript1/.tmp/qtjscript11.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.11 -Wl,-rpath,@executable_path/Frameworks
LIBS          = $(SUBLIBS) -L/usr/local/qt511/lib -lQt5Widgets_debug -framework DiskArbitration -framework IOKit -lQt5Gui_debug -lQt5Qml_debug -lQt5Network_debug -lQt5Core_debug -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		moc_mainwindow.o
DIST          = /usr/local/qt511/mkspecs/features/spec_pre.prf \
		/usr/local/qt511/mkspecs/qdevice.pri \
		/usr/local/qt511/mkspecs/features/device_config.prf \
		/usr/local/qt511/mkspecs/common/unix.conf \
		/usr/local/qt511/mkspecs/common/mac.conf \
		/usr/local/qt511/mkspecs/common/macx.conf \
		/usr/local/qt511/mkspecs/common/sanitize.conf \
		/usr/local/qt511/mkspecs/common/gcc-base.conf \
		/usr/local/qt511/mkspecs/common/gcc-base-mac.conf \
		/usr/local/qt511/mkspecs/common/clang.conf \
		/usr/local/qt511/mkspecs/common/clang-mac.conf \
		/usr/local/qt511/mkspecs/qconfig.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_core.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_enginio.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_enginio_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_network.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/qt511/mkspecs/features/qt_functions.prf \
		/usr/local/qt511/mkspecs/features/qt_config.prf \
		/usr/local/qt511/mkspecs/macx-clang/qmake.conf \
		/usr/local/qt511/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/qt511/mkspecs/features/exclusive_builds.prf \
		/usr/local/qt511/mkspecs/features/mac/sdk.prf \
		/usr/local/qt511/mkspecs/features/toolchain.prf \
		/usr/local/qt511/mkspecs/features/mac/toolchain.prf \
		/usr/local/qt511/mkspecs/features/default_pre.prf \
		/usr/local/qt511/mkspecs/features/mac/default_pre.prf \
		/usr/local/qt511/mkspecs/features/resolve_config.prf \
		/usr/local/qt511/mkspecs/features/default_post.prf \
		/usr/local/qt511/mkspecs/features/mac/default_post.prf \
		/usr/local/qt511/mkspecs/features/mac/objective_c.prf \
		/usr/local/qt511/mkspecs/features/mac/mac.prf \
		/usr/local/qt511/mkspecs/features/warn_on.prf \
		/usr/local/qt511/mkspecs/features/qt.prf \
		/usr/local/qt511/mkspecs/features/resources.prf \
		/usr/local/qt511/mkspecs/features/moc.prf \
		/usr/local/qt511/mkspecs/features/unix/opengl.prf \
		/usr/local/qt511/mkspecs/features/uic.prf \
		/usr/local/qt511/mkspecs/features/unix/thread.prf \
		/usr/local/qt511/mkspecs/features/qmake_use.prf \
		/usr/local/qt511/mkspecs/features/file_copies.prf \
		/usr/local/qt511/mkspecs/features/mac/rez.prf \
		/usr/local/qt511/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/qt511/mkspecs/features/testcase_targets.prf \
		/usr/local/qt511/mkspecs/features/exceptions.prf \
		/usr/local/qt511/mkspecs/features/yacc.prf \
		/usr/local/qt511/mkspecs/features/lex.prf \
		qtjscript1.pro mainwindow.h main.cpp \
		mainwindow.cpp
QMAKE_TARGET  = qtjscript1
DESTDIR       = 
TARGET        = qtjscript1.app/Contents/MacOS/qtjscript1

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.14
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


include /usr/local/qt511/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d qtjscript1.app/Contents/MacOS/ || mkdir -p qtjscript1.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qtjscript1.pro /usr/local/qt511/mkspecs/macx-clang/qmake.conf /usr/local/qt511/mkspecs/features/spec_pre.prf \
		/usr/local/qt511/mkspecs/qdevice.pri \
		/usr/local/qt511/mkspecs/features/device_config.prf \
		/usr/local/qt511/mkspecs/common/unix.conf \
		/usr/local/qt511/mkspecs/common/mac.conf \
		/usr/local/qt511/mkspecs/common/macx.conf \
		/usr/local/qt511/mkspecs/common/sanitize.conf \
		/usr/local/qt511/mkspecs/common/gcc-base.conf \
		/usr/local/qt511/mkspecs/common/gcc-base-mac.conf \
		/usr/local/qt511/mkspecs/common/clang.conf \
		/usr/local/qt511/mkspecs/common/clang-mac.conf \
		/usr/local/qt511/mkspecs/qconfig.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_core.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_enginio.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_enginio_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_network.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/qt511/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/qt511/mkspecs/features/qt_functions.prf \
		/usr/local/qt511/mkspecs/features/qt_config.prf \
		/usr/local/qt511/mkspecs/macx-clang/qmake.conf \
		/usr/local/qt511/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/qt511/mkspecs/features/exclusive_builds.prf \
		/usr/local/qt511/mkspecs/features/mac/sdk.prf \
		/usr/local/qt511/mkspecs/features/toolchain.prf \
		/usr/local/qt511/mkspecs/features/mac/toolchain.prf \
		/usr/local/qt511/mkspecs/features/default_pre.prf \
		/usr/local/qt511/mkspecs/features/mac/default_pre.prf \
		/usr/local/qt511/mkspecs/features/resolve_config.prf \
		/usr/local/qt511/mkspecs/features/default_post.prf \
		/usr/local/qt511/mkspecs/features/mac/default_post.prf \
		/usr/local/qt511/mkspecs/features/mac/objective_c.prf \
		/usr/local/qt511/mkspecs/features/mac/mac.prf \
		/usr/local/qt511/mkspecs/features/warn_on.prf \
		/usr/local/qt511/mkspecs/features/qt.prf \
		/usr/local/qt511/mkspecs/features/resources.prf \
		/usr/local/qt511/mkspecs/features/moc.prf \
		/usr/local/qt511/mkspecs/features/unix/opengl.prf \
		/usr/local/qt511/mkspecs/features/uic.prf \
		/usr/local/qt511/mkspecs/features/unix/thread.prf \
		/usr/local/qt511/mkspecs/features/qmake_use.prf \
		/usr/local/qt511/mkspecs/features/file_copies.prf \
		/usr/local/qt511/mkspecs/features/mac/rez.prf \
		/usr/local/qt511/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/qt511/mkspecs/features/testcase_targets.prf \
		/usr/local/qt511/mkspecs/features/exceptions.prf \
		/usr/local/qt511/mkspecs/features/yacc.prf \
		/usr/local/qt511/mkspecs/features/lex.prf \
		qtjscript1.pro \
		/usr/local/qt511/lib/libQt5Widgets_debug.prl \
		/usr/local/qt511/lib/libQt5Gui_debug.prl \
		/usr/local/qt511/lib/libQt5Qml_debug.prl \
		/usr/local/qt511/lib/libQt5Network_debug.prl \
		/usr/local/qt511/lib/libQt5Core_debug.prl
	$(QMAKE) -o Makefile qtjscript1.pro
/usr/local/qt511/mkspecs/features/spec_pre.prf:
/usr/local/qt511/mkspecs/qdevice.pri:
/usr/local/qt511/mkspecs/features/device_config.prf:
/usr/local/qt511/mkspecs/common/unix.conf:
/usr/local/qt511/mkspecs/common/mac.conf:
/usr/local/qt511/mkspecs/common/macx.conf:
/usr/local/qt511/mkspecs/common/sanitize.conf:
/usr/local/qt511/mkspecs/common/gcc-base.conf:
/usr/local/qt511/mkspecs/common/gcc-base-mac.conf:
/usr/local/qt511/mkspecs/common/clang.conf:
/usr/local/qt511/mkspecs/common/clang-mac.conf:
/usr/local/qt511/mkspecs/qconfig.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_core.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_enginio.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_enginio_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_gamepad.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_graphics_support_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_gui.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_macextras.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_macextras_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_network.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_networkauth.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_purchasing.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_purchasing_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_qml.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_quick.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_repparser.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_sql.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_svg.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_xml.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/qt511/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/qt511/mkspecs/features/qt_functions.prf:
/usr/local/qt511/mkspecs/features/qt_config.prf:
/usr/local/qt511/mkspecs/macx-clang/qmake.conf:
/usr/local/qt511/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/qt511/mkspecs/features/exclusive_builds.prf:
/usr/local/qt511/mkspecs/features/mac/sdk.prf:
/usr/local/qt511/mkspecs/features/toolchain.prf:
/usr/local/qt511/mkspecs/features/mac/toolchain.prf:
/usr/local/qt511/mkspecs/features/default_pre.prf:
/usr/local/qt511/mkspecs/features/mac/default_pre.prf:
/usr/local/qt511/mkspecs/features/resolve_config.prf:
/usr/local/qt511/mkspecs/features/default_post.prf:
/usr/local/qt511/mkspecs/features/mac/default_post.prf:
/usr/local/qt511/mkspecs/features/mac/objective_c.prf:
/usr/local/qt511/mkspecs/features/mac/mac.prf:
/usr/local/qt511/mkspecs/features/warn_on.prf:
/usr/local/qt511/mkspecs/features/qt.prf:
/usr/local/qt511/mkspecs/features/resources.prf:
/usr/local/qt511/mkspecs/features/moc.prf:
/usr/local/qt511/mkspecs/features/unix/opengl.prf:
/usr/local/qt511/mkspecs/features/uic.prf:
/usr/local/qt511/mkspecs/features/unix/thread.prf:
/usr/local/qt511/mkspecs/features/qmake_use.prf:
/usr/local/qt511/mkspecs/features/file_copies.prf:
/usr/local/qt511/mkspecs/features/mac/rez.prf:
/usr/local/qt511/mkspecs/features/mac/asset_catalogs.prf:
/usr/local/qt511/mkspecs/features/testcase_targets.prf:
/usr/local/qt511/mkspecs/features/exceptions.prf:
/usr/local/qt511/mkspecs/features/yacc.prf:
/usr/local/qt511/mkspecs/features/lex.prf:
qtjscript1.pro:
/usr/local/qt511/lib/libQt5Widgets_debug.prl:
/usr/local/qt511/lib/libQt5Gui_debug.prl:
/usr/local/qt511/lib/libQt5Qml_debug.prl:
/usr/local/qt511/lib/libQt5Network_debug.prl:
/usr/local/qt511/lib/libQt5Core_debug.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile qtjscript1.pro

qmake_all: FORCE

qtjscript1.app/Contents/PkgInfo: 
	@test -d qtjscript1.app/Contents || mkdir -p qtjscript1.app/Contents
	@$(DEL_FILE) qtjscript1.app/Contents/PkgInfo
	@echo "APPL????" > qtjscript1.app/Contents/PkgInfo
qtjscript1.app/Contents/Resources/empty.lproj: 
	@test -d qtjscript1.app/Contents/Resources || mkdir -p qtjscript1.app/Contents/Resources
	@touch qtjscript1.app/Contents/Resources/empty.lproj
	
qtjscript1.app/Contents/Info.plist: 
	@test -d qtjscript1.app/Contents || mkdir -p qtjscript1.app/Contents
	@$(DEL_FILE) qtjscript1.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,dust.qtjscript1,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},dust.qtjscript1,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.11,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,qtjscript1,g" -e "s,@LIBRARY@,qtjscript1,g" -e "s,\$${EXECUTABLE_NAME},qtjscript1,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" /usr/local/qt511/mkspecs/macx-clang/Info.plist.app >qtjscript1.app/Contents/Info.plist

all: Makefile \
		qtjscript1.app/Contents/PkgInfo \
		qtjscript1.app/Contents/Resources/empty.lproj \
		qtjscript1.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/local/qt511/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r qtjscript1.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/local/qt511/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.11 -Wall -W -dM -E -o moc_predefs.h /usr/local/qt511/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: /usr/local/qt511/include/QtWidgets/QMainWindow \
		/usr/local/qt511/include/QtWidgets/qmainwindow.h \
		/usr/local/qt511/include/QtWidgets/qtwidgetsglobal.h \
		/usr/local/qt511/include/QtGui/qtguiglobal.h \
		/usr/local/qt511/include/QtCore/qglobal.h \
		/usr/local/qt511/include/QtCore/qconfig-bootstrapped.h \
		/usr/local/qt511/include/QtCore/qconfig.h \
		/usr/local/qt511/include/QtCore/qtcore-config.h \
		/usr/local/qt511/include/QtCore/qsystemdetection.h \
		/usr/local/qt511/include/QtCore/qprocessordetection.h \
		/usr/local/qt511/include/QtCore/qcompilerdetection.h \
		/usr/local/qt511/include/QtCore/qtypeinfo.h \
		/usr/local/qt511/include/QtCore/qsysinfo.h \
		/usr/local/qt511/include/QtCore/qlogging.h \
		/usr/local/qt511/include/QtCore/qflags.h \
		/usr/local/qt511/include/QtCore/qatomic.h \
		/usr/local/qt511/include/QtCore/qbasicatomic.h \
		/usr/local/qt511/include/QtCore/qatomic_bootstrap.h \
		/usr/local/qt511/include/QtCore/qgenericatomic.h \
		/usr/local/qt511/include/QtCore/qatomic_cxx11.h \
		/usr/local/qt511/include/QtCore/qatomic_msvc.h \
		/usr/local/qt511/include/QtCore/qglobalstatic.h \
		/usr/local/qt511/include/QtCore/qmutex.h \
		/usr/local/qt511/include/QtCore/qnumeric.h \
		/usr/local/qt511/include/QtCore/qversiontagging.h \
		/usr/local/qt511/include/QtGui/qtgui-config.h \
		/usr/local/qt511/include/QtWidgets/qtwidgets-config.h \
		/usr/local/qt511/include/QtWidgets/qwidget.h \
		/usr/local/qt511/include/QtGui/qwindowdefs.h \
		/usr/local/qt511/include/QtCore/qobjectdefs.h \
		/usr/local/qt511/include/QtCore/qnamespace.h \
		/usr/local/qt511/include/QtCore/qobjectdefs_impl.h \
		/usr/local/qt511/include/QtGui/qwindowdefs_win.h \
		/usr/local/qt511/include/QtCore/qobject.h \
		/usr/local/qt511/include/QtCore/qstring.h \
		/usr/local/qt511/include/QtCore/qchar.h \
		/usr/local/qt511/include/QtCore/qbytearray.h \
		/usr/local/qt511/include/QtCore/qrefcount.h \
		/usr/local/qt511/include/QtCore/qarraydata.h \
		/usr/local/qt511/include/QtCore/qstringliteral.h \
		/usr/local/qt511/include/QtCore/qstringalgorithms.h \
		/usr/local/qt511/include/QtCore/qstringview.h \
		/usr/local/qt511/include/QtCore/qstringbuilder.h \
		/usr/local/qt511/include/QtCore/qlist.h \
		/usr/local/qt511/include/QtCore/qalgorithms.h \
		/usr/local/qt511/include/QtCore/qiterator.h \
		/usr/local/qt511/include/QtCore/qhashfunctions.h \
		/usr/local/qt511/include/QtCore/qpair.h \
		/usr/local/qt511/include/QtCore/qbytearraylist.h \
		/usr/local/qt511/include/QtCore/qstringlist.h \
		/usr/local/qt511/include/QtCore/qregexp.h \
		/usr/local/qt511/include/QtCore/qstringmatcher.h \
		/usr/local/qt511/include/QtCore/qcoreevent.h \
		/usr/local/qt511/include/QtCore/qscopedpointer.h \
		/usr/local/qt511/include/QtCore/qmetatype.h \
		/usr/local/qt511/include/QtCore/qvarlengtharray.h \
		/usr/local/qt511/include/QtCore/qcontainerfwd.h \
		/usr/local/qt511/include/QtCore/qobject_impl.h \
		/usr/local/qt511/include/QtCore/qmargins.h \
		/usr/local/qt511/include/QtGui/qpaintdevice.h \
		/usr/local/qt511/include/QtCore/qrect.h \
		/usr/local/qt511/include/QtCore/qsize.h \
		/usr/local/qt511/include/QtCore/qpoint.h \
		/usr/local/qt511/include/QtGui/qpalette.h \
		/usr/local/qt511/include/QtGui/qcolor.h \
		/usr/local/qt511/include/QtGui/qrgb.h \
		/usr/local/qt511/include/QtGui/qrgba64.h \
		/usr/local/qt511/include/QtGui/qbrush.h \
		/usr/local/qt511/include/QtCore/qvector.h \
		/usr/local/qt511/include/QtGui/qmatrix.h \
		/usr/local/qt511/include/QtGui/qpolygon.h \
		/usr/local/qt511/include/QtGui/qregion.h \
		/usr/local/qt511/include/QtCore/qdatastream.h \
		/usr/local/qt511/include/QtCore/qiodevice.h \
		/usr/local/qt511/include/QtCore/qline.h \
		/usr/local/qt511/include/QtGui/qtransform.h \
		/usr/local/qt511/include/QtGui/qpainterpath.h \
		/usr/local/qt511/include/QtGui/qimage.h \
		/usr/local/qt511/include/QtGui/qpixelformat.h \
		/usr/local/qt511/include/QtGui/qpixmap.h \
		/usr/local/qt511/include/QtCore/qsharedpointer.h \
		/usr/local/qt511/include/QtCore/qshareddata.h \
		/usr/local/qt511/include/QtCore/qhash.h \
		/usr/local/qt511/include/QtCore/qsharedpointer_impl.h \
		/usr/local/qt511/include/QtGui/qfont.h \
		/usr/local/qt511/include/QtGui/qfontmetrics.h \
		/usr/local/qt511/include/QtGui/qfontinfo.h \
		/usr/local/qt511/include/QtWidgets/qsizepolicy.h \
		/usr/local/qt511/include/QtGui/qcursor.h \
		/usr/local/qt511/include/QtGui/qkeysequence.h \
		/usr/local/qt511/include/QtGui/qevent.h \
		/usr/local/qt511/include/QtCore/qvariant.h \
		/usr/local/qt511/include/QtCore/qmap.h \
		/usr/local/qt511/include/QtCore/qdebug.h \
		/usr/local/qt511/include/QtCore/qtextstream.h \
		/usr/local/qt511/include/QtCore/qlocale.h \
		/usr/local/qt511/include/QtCore/qset.h \
		/usr/local/qt511/include/QtCore/qcontiguouscache.h \
		/usr/local/qt511/include/QtCore/qurl.h \
		/usr/local/qt511/include/QtCore/qurlquery.h \
		/usr/local/qt511/include/QtCore/qfile.h \
		/usr/local/qt511/include/QtCore/qfiledevice.h \
		/usr/local/qt511/include/QtGui/qvector2d.h \
		/usr/local/qt511/include/QtGui/qtouchdevice.h \
		/usr/local/qt511/include/QtWidgets/qtabwidget.h \
		/usr/local/qt511/include/QtGui/qicon.h \
		/usr/local/qt511/include/QtQml/qjsengine.h \
		/usr/local/qt511/include/QtQml/qjsvalue.h \
		/usr/local/qt511/include/QtQml/qtqmlglobal.h \
		/usr/local/qt511/include/QtQml/qtqml-config.h \
		/usr/local/qt511/include/QtNetwork/qtnetworkglobal.h \
		/usr/local/qt511/include/QtNetwork/qtnetwork-config.h \
		/usr/local/qt511/include/QtQml/qqmldebug.h \
		mainwindow.h \
		moc_predefs.h \
		/usr/local/qt511/bin/moc
	/usr/local/qt511/bin/moc $(DEFINES) --include /Users/jjosburn/Documents/programming/qtjscript1/moc_predefs.h -I/usr/local/qt511/mkspecs/macx-clang -I/Users/jjosburn/Documents/programming/qtjscript1 -I/usr/local/qt511/include -I/usr/local/qt511/include/QtWidgets -I/usr/local/qt511/include/QtGui -I/usr/local/qt511/include/QtQml -I/usr/local/qt511/include/QtNetwork -I/usr/local/qt511/include/QtCore -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		/usr/local/qt511/bin/uic
	/usr/local/qt511/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/usr/local/qt511/include/QtWidgets/QMainWindow \
		/usr/local/qt511/include/QtWidgets/qmainwindow.h \
		/usr/local/qt511/include/QtWidgets/qtwidgetsglobal.h \
		/usr/local/qt511/include/QtGui/qtguiglobal.h \
		/usr/local/qt511/include/QtCore/qglobal.h \
		/usr/local/qt511/include/QtCore/qconfig-bootstrapped.h \
		/usr/local/qt511/include/QtCore/qconfig.h \
		/usr/local/qt511/include/QtCore/qtcore-config.h \
		/usr/local/qt511/include/QtCore/qsystemdetection.h \
		/usr/local/qt511/include/QtCore/qprocessordetection.h \
		/usr/local/qt511/include/QtCore/qcompilerdetection.h \
		/usr/local/qt511/include/QtCore/qtypeinfo.h \
		/usr/local/qt511/include/QtCore/qsysinfo.h \
		/usr/local/qt511/include/QtCore/qlogging.h \
		/usr/local/qt511/include/QtCore/qflags.h \
		/usr/local/qt511/include/QtCore/qatomic.h \
		/usr/local/qt511/include/QtCore/qbasicatomic.h \
		/usr/local/qt511/include/QtCore/qatomic_bootstrap.h \
		/usr/local/qt511/include/QtCore/qgenericatomic.h \
		/usr/local/qt511/include/QtCore/qatomic_cxx11.h \
		/usr/local/qt511/include/QtCore/qatomic_msvc.h \
		/usr/local/qt511/include/QtCore/qglobalstatic.h \
		/usr/local/qt511/include/QtCore/qmutex.h \
		/usr/local/qt511/include/QtCore/qnumeric.h \
		/usr/local/qt511/include/QtCore/qversiontagging.h \
		/usr/local/qt511/include/QtGui/qtgui-config.h \
		/usr/local/qt511/include/QtWidgets/qtwidgets-config.h \
		/usr/local/qt511/include/QtWidgets/qwidget.h \
		/usr/local/qt511/include/QtGui/qwindowdefs.h \
		/usr/local/qt511/include/QtCore/qobjectdefs.h \
		/usr/local/qt511/include/QtCore/qnamespace.h \
		/usr/local/qt511/include/QtCore/qobjectdefs_impl.h \
		/usr/local/qt511/include/QtGui/qwindowdefs_win.h \
		/usr/local/qt511/include/QtCore/qobject.h \
		/usr/local/qt511/include/QtCore/qstring.h \
		/usr/local/qt511/include/QtCore/qchar.h \
		/usr/local/qt511/include/QtCore/qbytearray.h \
		/usr/local/qt511/include/QtCore/qrefcount.h \
		/usr/local/qt511/include/QtCore/qarraydata.h \
		/usr/local/qt511/include/QtCore/qstringliteral.h \
		/usr/local/qt511/include/QtCore/qstringalgorithms.h \
		/usr/local/qt511/include/QtCore/qstringview.h \
		/usr/local/qt511/include/QtCore/qstringbuilder.h \
		/usr/local/qt511/include/QtCore/qlist.h \
		/usr/local/qt511/include/QtCore/qalgorithms.h \
		/usr/local/qt511/include/QtCore/qiterator.h \
		/usr/local/qt511/include/QtCore/qhashfunctions.h \
		/usr/local/qt511/include/QtCore/qpair.h \
		/usr/local/qt511/include/QtCore/qbytearraylist.h \
		/usr/local/qt511/include/QtCore/qstringlist.h \
		/usr/local/qt511/include/QtCore/qregexp.h \
		/usr/local/qt511/include/QtCore/qstringmatcher.h \
		/usr/local/qt511/include/QtCore/qcoreevent.h \
		/usr/local/qt511/include/QtCore/qscopedpointer.h \
		/usr/local/qt511/include/QtCore/qmetatype.h \
		/usr/local/qt511/include/QtCore/qvarlengtharray.h \
		/usr/local/qt511/include/QtCore/qcontainerfwd.h \
		/usr/local/qt511/include/QtCore/qobject_impl.h \
		/usr/local/qt511/include/QtCore/qmargins.h \
		/usr/local/qt511/include/QtGui/qpaintdevice.h \
		/usr/local/qt511/include/QtCore/qrect.h \
		/usr/local/qt511/include/QtCore/qsize.h \
		/usr/local/qt511/include/QtCore/qpoint.h \
		/usr/local/qt511/include/QtGui/qpalette.h \
		/usr/local/qt511/include/QtGui/qcolor.h \
		/usr/local/qt511/include/QtGui/qrgb.h \
		/usr/local/qt511/include/QtGui/qrgba64.h \
		/usr/local/qt511/include/QtGui/qbrush.h \
		/usr/local/qt511/include/QtCore/qvector.h \
		/usr/local/qt511/include/QtGui/qmatrix.h \
		/usr/local/qt511/include/QtGui/qpolygon.h \
		/usr/local/qt511/include/QtGui/qregion.h \
		/usr/local/qt511/include/QtCore/qdatastream.h \
		/usr/local/qt511/include/QtCore/qiodevice.h \
		/usr/local/qt511/include/QtCore/qline.h \
		/usr/local/qt511/include/QtGui/qtransform.h \
		/usr/local/qt511/include/QtGui/qpainterpath.h \
		/usr/local/qt511/include/QtGui/qimage.h \
		/usr/local/qt511/include/QtGui/qpixelformat.h \
		/usr/local/qt511/include/QtGui/qpixmap.h \
		/usr/local/qt511/include/QtCore/qsharedpointer.h \
		/usr/local/qt511/include/QtCore/qshareddata.h \
		/usr/local/qt511/include/QtCore/qhash.h \
		/usr/local/qt511/include/QtCore/qsharedpointer_impl.h \
		/usr/local/qt511/include/QtGui/qfont.h \
		/usr/local/qt511/include/QtGui/qfontmetrics.h \
		/usr/local/qt511/include/QtGui/qfontinfo.h \
		/usr/local/qt511/include/QtWidgets/qsizepolicy.h \
		/usr/local/qt511/include/QtGui/qcursor.h \
		/usr/local/qt511/include/QtGui/qkeysequence.h \
		/usr/local/qt511/include/QtGui/qevent.h \
		/usr/local/qt511/include/QtCore/qvariant.h \
		/usr/local/qt511/include/QtCore/qmap.h \
		/usr/local/qt511/include/QtCore/qdebug.h \
		/usr/local/qt511/include/QtCore/qtextstream.h \
		/usr/local/qt511/include/QtCore/qlocale.h \
		/usr/local/qt511/include/QtCore/qset.h \
		/usr/local/qt511/include/QtCore/qcontiguouscache.h \
		/usr/local/qt511/include/QtCore/qurl.h \
		/usr/local/qt511/include/QtCore/qurlquery.h \
		/usr/local/qt511/include/QtCore/qfile.h \
		/usr/local/qt511/include/QtCore/qfiledevice.h \
		/usr/local/qt511/include/QtGui/qvector2d.h \
		/usr/local/qt511/include/QtGui/qtouchdevice.h \
		/usr/local/qt511/include/QtWidgets/qtabwidget.h \
		/usr/local/qt511/include/QtGui/qicon.h \
		/usr/local/qt511/include/QtQml/qjsengine.h \
		/usr/local/qt511/include/QtQml/qjsvalue.h \
		/usr/local/qt511/include/QtQml/qtqmlglobal.h \
		/usr/local/qt511/include/QtQml/qtqml-config.h \
		/usr/local/qt511/include/QtNetwork/qtnetworkglobal.h \
		/usr/local/qt511/include/QtNetwork/qtnetwork-config.h \
		/usr/local/qt511/include/QtQml/qqmldebug.h \
		/usr/local/qt511/include/QtWidgets/QApplication \
		/usr/local/qt511/include/QtWidgets/qapplication.h \
		/usr/local/qt511/include/QtCore/qcoreapplication.h \
		/usr/local/qt511/include/QtCore/qeventloop.h \
		/usr/local/qt511/include/QtWidgets/qdesktopwidget.h \
		/usr/local/qt511/include/QtGui/qguiapplication.h \
		/usr/local/qt511/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/usr/local/qt511/include/QtWidgets/QMainWindow \
		/usr/local/qt511/include/QtWidgets/qmainwindow.h \
		/usr/local/qt511/include/QtWidgets/qtwidgetsglobal.h \
		/usr/local/qt511/include/QtGui/qtguiglobal.h \
		/usr/local/qt511/include/QtCore/qglobal.h \
		/usr/local/qt511/include/QtCore/qconfig-bootstrapped.h \
		/usr/local/qt511/include/QtCore/qconfig.h \
		/usr/local/qt511/include/QtCore/qtcore-config.h \
		/usr/local/qt511/include/QtCore/qsystemdetection.h \
		/usr/local/qt511/include/QtCore/qprocessordetection.h \
		/usr/local/qt511/include/QtCore/qcompilerdetection.h \
		/usr/local/qt511/include/QtCore/qtypeinfo.h \
		/usr/local/qt511/include/QtCore/qsysinfo.h \
		/usr/local/qt511/include/QtCore/qlogging.h \
		/usr/local/qt511/include/QtCore/qflags.h \
		/usr/local/qt511/include/QtCore/qatomic.h \
		/usr/local/qt511/include/QtCore/qbasicatomic.h \
		/usr/local/qt511/include/QtCore/qatomic_bootstrap.h \
		/usr/local/qt511/include/QtCore/qgenericatomic.h \
		/usr/local/qt511/include/QtCore/qatomic_cxx11.h \
		/usr/local/qt511/include/QtCore/qatomic_msvc.h \
		/usr/local/qt511/include/QtCore/qglobalstatic.h \
		/usr/local/qt511/include/QtCore/qmutex.h \
		/usr/local/qt511/include/QtCore/qnumeric.h \
		/usr/local/qt511/include/QtCore/qversiontagging.h \
		/usr/local/qt511/include/QtGui/qtgui-config.h \
		/usr/local/qt511/include/QtWidgets/qtwidgets-config.h \
		/usr/local/qt511/include/QtWidgets/qwidget.h \
		/usr/local/qt511/include/QtGui/qwindowdefs.h \
		/usr/local/qt511/include/QtCore/qobjectdefs.h \
		/usr/local/qt511/include/QtCore/qnamespace.h \
		/usr/local/qt511/include/QtCore/qobjectdefs_impl.h \
		/usr/local/qt511/include/QtGui/qwindowdefs_win.h \
		/usr/local/qt511/include/QtCore/qobject.h \
		/usr/local/qt511/include/QtCore/qstring.h \
		/usr/local/qt511/include/QtCore/qchar.h \
		/usr/local/qt511/include/QtCore/qbytearray.h \
		/usr/local/qt511/include/QtCore/qrefcount.h \
		/usr/local/qt511/include/QtCore/qarraydata.h \
		/usr/local/qt511/include/QtCore/qstringliteral.h \
		/usr/local/qt511/include/QtCore/qstringalgorithms.h \
		/usr/local/qt511/include/QtCore/qstringview.h \
		/usr/local/qt511/include/QtCore/qstringbuilder.h \
		/usr/local/qt511/include/QtCore/qlist.h \
		/usr/local/qt511/include/QtCore/qalgorithms.h \
		/usr/local/qt511/include/QtCore/qiterator.h \
		/usr/local/qt511/include/QtCore/qhashfunctions.h \
		/usr/local/qt511/include/QtCore/qpair.h \
		/usr/local/qt511/include/QtCore/qbytearraylist.h \
		/usr/local/qt511/include/QtCore/qstringlist.h \
		/usr/local/qt511/include/QtCore/qregexp.h \
		/usr/local/qt511/include/QtCore/qstringmatcher.h \
		/usr/local/qt511/include/QtCore/qcoreevent.h \
		/usr/local/qt511/include/QtCore/qscopedpointer.h \
		/usr/local/qt511/include/QtCore/qmetatype.h \
		/usr/local/qt511/include/QtCore/qvarlengtharray.h \
		/usr/local/qt511/include/QtCore/qcontainerfwd.h \
		/usr/local/qt511/include/QtCore/qobject_impl.h \
		/usr/local/qt511/include/QtCore/qmargins.h \
		/usr/local/qt511/include/QtGui/qpaintdevice.h \
		/usr/local/qt511/include/QtCore/qrect.h \
		/usr/local/qt511/include/QtCore/qsize.h \
		/usr/local/qt511/include/QtCore/qpoint.h \
		/usr/local/qt511/include/QtGui/qpalette.h \
		/usr/local/qt511/include/QtGui/qcolor.h \
		/usr/local/qt511/include/QtGui/qrgb.h \
		/usr/local/qt511/include/QtGui/qrgba64.h \
		/usr/local/qt511/include/QtGui/qbrush.h \
		/usr/local/qt511/include/QtCore/qvector.h \
		/usr/local/qt511/include/QtGui/qmatrix.h \
		/usr/local/qt511/include/QtGui/qpolygon.h \
		/usr/local/qt511/include/QtGui/qregion.h \
		/usr/local/qt511/include/QtCore/qdatastream.h \
		/usr/local/qt511/include/QtCore/qiodevice.h \
		/usr/local/qt511/include/QtCore/qline.h \
		/usr/local/qt511/include/QtGui/qtransform.h \
		/usr/local/qt511/include/QtGui/qpainterpath.h \
		/usr/local/qt511/include/QtGui/qimage.h \
		/usr/local/qt511/include/QtGui/qpixelformat.h \
		/usr/local/qt511/include/QtGui/qpixmap.h \
		/usr/local/qt511/include/QtCore/qsharedpointer.h \
		/usr/local/qt511/include/QtCore/qshareddata.h \
		/usr/local/qt511/include/QtCore/qhash.h \
		/usr/local/qt511/include/QtCore/qsharedpointer_impl.h \
		/usr/local/qt511/include/QtGui/qfont.h \
		/usr/local/qt511/include/QtGui/qfontmetrics.h \
		/usr/local/qt511/include/QtGui/qfontinfo.h \
		/usr/local/qt511/include/QtWidgets/qsizepolicy.h \
		/usr/local/qt511/include/QtGui/qcursor.h \
		/usr/local/qt511/include/QtGui/qkeysequence.h \
		/usr/local/qt511/include/QtGui/qevent.h \
		/usr/local/qt511/include/QtCore/qvariant.h \
		/usr/local/qt511/include/QtCore/qmap.h \
		/usr/local/qt511/include/QtCore/qdebug.h \
		/usr/local/qt511/include/QtCore/qtextstream.h \
		/usr/local/qt511/include/QtCore/qlocale.h \
		/usr/local/qt511/include/QtCore/qset.h \
		/usr/local/qt511/include/QtCore/qcontiguouscache.h \
		/usr/local/qt511/include/QtCore/qurl.h \
		/usr/local/qt511/include/QtCore/qurlquery.h \
		/usr/local/qt511/include/QtCore/qfile.h \
		/usr/local/qt511/include/QtCore/qfiledevice.h \
		/usr/local/qt511/include/QtGui/qvector2d.h \
		/usr/local/qt511/include/QtGui/qtouchdevice.h \
		/usr/local/qt511/include/QtWidgets/qtabwidget.h \
		/usr/local/qt511/include/QtGui/qicon.h \
		/usr/local/qt511/include/QtQml/qjsengine.h \
		/usr/local/qt511/include/QtQml/qjsvalue.h \
		/usr/local/qt511/include/QtQml/qtqmlglobal.h \
		/usr/local/qt511/include/QtQml/qtqml-config.h \
		/usr/local/qt511/include/QtNetwork/qtnetworkglobal.h \
		/usr/local/qt511/include/QtNetwork/qtnetwork-config.h \
		/usr/local/qt511/include/QtQml/qqmldebug.h \
		ui_mainwindow.h \
		/usr/local/qt511/include/QtCore/QVariant \
		/usr/local/qt511/include/QtWidgets/QApplication \
		/usr/local/qt511/include/QtWidgets/qapplication.h \
		/usr/local/qt511/include/QtCore/qcoreapplication.h \
		/usr/local/qt511/include/QtCore/qeventloop.h \
		/usr/local/qt511/include/QtWidgets/qdesktopwidget.h \
		/usr/local/qt511/include/QtGui/qguiapplication.h \
		/usr/local/qt511/include/QtGui/qinputmethod.h \
		/usr/local/qt511/include/QtWidgets/QMenuBar \
		/usr/local/qt511/include/QtWidgets/qmenubar.h \
		/usr/local/qt511/include/QtWidgets/qmenu.h \
		/usr/local/qt511/include/QtWidgets/qaction.h \
		/usr/local/qt511/include/QtWidgets/qactiongroup.h \
		/usr/local/qt511/include/QtWidgets/QPushButton \
		/usr/local/qt511/include/QtWidgets/qpushbutton.h \
		/usr/local/qt511/include/QtWidgets/qabstractbutton.h \
		/usr/local/qt511/include/QtWidgets/QStatusBar \
		/usr/local/qt511/include/QtWidgets/qstatusbar.h \
		/usr/local/qt511/include/QtWidgets/QToolBar \
		/usr/local/qt511/include/QtWidgets/qtoolbar.h \
		/usr/local/qt511/include/QtWidgets/QWidget \
		/usr/local/qt511/include/QtWidgets/QFileDialog \
		/usr/local/qt511/include/QtWidgets/qfiledialog.h \
		/usr/local/qt511/include/QtCore/qdir.h \
		/usr/local/qt511/include/QtCore/qfileinfo.h \
		/usr/local/qt511/include/QtWidgets/qdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

